name: 'checkout github repo'
description: 'Clone github repo and checkout commit'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  submodules:
    description: 'init submodules, can be true or false'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: clone repo
      run: |
        git clone https://${{ github.token }}@github.com/${{ github.repository }} .
        git checkout ${{ github.sha }}

        if [ "${{ inputs.submodules }}" == "true" ]; then
          # replace ssh to https in .gitmodules
          sed -E -i -e 's/^\s*url\s*=\s*git@github.com:([^\/]*\/[^\/]*)\s*$/\turl = https:\/\/${{ github.token }}@github.com\/\1/g' .gitmodules
          git submodule init
          git submodule update --recursive
        fi
      shell: bash
